### ISSUE TITLE
Individual users not removed if only teams are listed as collaborators

### ISSUE THREAD

**Issue by sparkythehuman** [farmdawgnation/repo-policy#32]
For example: 
```
name: Acme Repo Policy
version: 1.0
author: Josh
rules:
  - org: AcmeCorp
    topic: null
    # Rules match on a topic set on the repository and apply repo
    # and branch settings. You can omit the topic parameter or set
    # it to null to have this apply to all repositories owned by a
    # particular owner.
    repo:
      collaborators:
        - org: AcmeCorp
          name: Engineering
          permission: write
```

This will not add/remove individual users from the repos on `enforce`.
